export const CORE_PRISMA_CLIENT = Symbol('CORE_PRISMA_CLIENT');
export const VOLATILE_PRISMA_CLIENT = Symbol('VOLATILE_PRISMA_CLIENT');
export const TENANT_PRISMA_FACTORY = Symbol('TENANT_PRISMA_FACTORY');
